# Generated by Django 4.2.3 on 2023-07-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Duration of the service in minutes'),
        ),
    ]
