# Generated by Django 4.1.7 on 2023-07-31 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_duration_minutes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='duration_minutes',
            new_name='duration',
        ),
    ]
