# Generated by Django 4.2.3 on 2023-07-19 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0002_workschedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkSchedule',
        ),
    ]
