# Generated by Django 4.1.7 on 2023-07-30 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0003_alter_master_user_alter_workschedule_work_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='master',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='WorkSchedule',
        ),
        migrations.AddField(
            model_name='timeslot',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.master'),
        ),
    ]
