# Generated by Django 4.1.7 on 2023-07-30 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0005_workschedule_delete_timeslot_master_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='master',
            name='schedule',
        ),
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='WorkSchedule',
        ),
    ]
