# Generated by Django 4.2.3 on 2023-07-15 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
