# Generated by Django 4.2.3 on 2023-07-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='scheduled', max_length=20),
        ),
    ]
